<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Lotauction extends Model
{
    use HasFactory;

    protected $fillable = [
        'name_lot',
        'start_date',
        'end_date',
        'starting_price',
        'rate_id',
        'create_user_id'
    ];

    public function rates(): BelongsTo
    {
        return $this->belongsTo(Rate::class, 'rate_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        if (auth()->check())
        {
            self::creating(function ($model)
            {
                if ($model->create_user_id == null)
                {
                    $model->create_user_id = auth()->id();
                }
            });
        }
    }

}
